apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: team12
spec:
  selector:
    app: c3m
  ports:
    - protocol: TCP
      port: 27017      
      targetPort: 27017
  type: ClusterIP
