apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-consumer
  namespace: team12
spec:
  selector:
    matchLabels:
      app: ml-consumer 
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-consumer 
    spec:
      containers:
      - name: ml-consumer
        image: docker.io/allx2100/ml-consumer # Used personal docker hub account since registries were full
        ports:
        - containerPort: 9092 
